name: check_syntax

on:
  push:
    branches:
      - main

jobs:
  syntax-check:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]
        os: [windows-latest, ubuntu-latest]

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Update pip
        run: |
          python -m pip install --upgrade pip

      - name: Display Python version
        run: python --version

      - name: Install flake8
        run: |
          python -m pip install flake8

      - name: Run flake8
        run: |
          flake8 .

      - name: Run unittest
        run: |
          python -m unittest discover
          python -m unittest discover
